name: Testing Go

on: [push, pull_request]

jobs:
  test-go:
    name: Testing Go Solutions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - run: go test ./...
